#version: '3.8'
#
#services:
#  zookeeper:
#    container_name: zookeeper
#    image: zookeeper
#    ports:
#      - 2181:2181
#
#  kafka:
#    container_name: kafka
#    image: wurstmeister/kafka
#    ports:
#      - 9092:9092
#    environment:
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./data/kafka:/kafka
#
#  mongo:
#    container_name: ecom-mongo-service
#    image: mongo
#    ports:
#      - 27017:27017
#    volumes:
#      - ./data/mongo:/data/db
#
#  ecom-aws-cloud-server:
#    container_name: ecom-aws-cloud
#    build: .
#    ports:
#      - 4009:4009
#    volumes:
#      - .:/usr/src/app
#    environment:
#      - PORT=4009
#      - KAFKA_HOST=kafka:9092
#      - KAFKA_TOPIC=todo-topic
#    depends_on:
#      - mongo
#      - kafka


version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka

  mongo:
    container_name: ecom-mongo-service
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  ecom-aws-cloud-server:
    container_name: ecom-aws-cloud
    build: .
    ports:
      - 4009:4009
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=4009
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=todo-topic
      - MONGODB_URI=mongodb://ecom-mongo-service:27017/node-ecom-ms
    depends_on:
      - mongo
      - kafka